schema interop additions
oasis-open/cti-stix2-json-schemas pull request #146
Opened 2022-04-01 15:17 UTC by jweissm

2022-06-15 17:19 UTC, clenk commented
Tests will continue to fail until `ajv-cli` resolves this issue: https://github.com/ajv-validator/ajv-cli/issues/172

2022-06-15 17:25 UTC, clenk requested changes
1. These 2 also need to switch to draft/2020-12:
- schemas/common/core.json
- schemas/sros/sighting.json

2. In `test_examples.sh`, `ajv` needs to use `--spec=draft2020`. I think we can remove the `-c ajv-formats-draft2019` option.

2022-06-17 13:14 UTC, clenk commented on interop/intrusion-set.json
> +        "resource_leve",
Typo!
```suggestion
        "resource_level",
```

2022-08-05 19:15 UTC, clenk commented
This looks good to me.

2022-08-05 23:08 UTC, ejratl commented
Merging this will require an update to the workflows as well, specifically
https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/.github/workflows/python-ci-tests.yml#L28
installs ajv-formats-draft2019. The test-example.sh shows errors but does not error out, so the check passes but with errors.

2022-08-05 23:30 UTC, ejratl commented
After the change in PR#154, it still isn't entirely happy since the schemas already existed.

2022-08-05 23:31 UTC, merged